

export const RECEIVE_BABY = "RECEIVE_BABY"



export const RECEIVE_DIAPERS = "RECEIVE_DIAPERS"
export const RECEIVE_FEEDING = "RECEIVE_FEEDING"
export const RECEIVE_WEIGHT = "RECEIVE_WEIGHT"
export const RECEIVE_HEIGHT = "RECEIVE_HEIGHT"
export const RECEIVE_SLEEP = 'RECEIVE_SLEEP'

export const RECEIVE_PARENT = "RECEIVE_PARENT"
export const ADD_BABY = "ADD_BABY"
export const DELETE_BABY = "DELETE_BABY"
